{% set name = "skelly-viewer" %}
{% set version = "2025.4.1028" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/skelly_viewer-{{ version }}.tar.gz
  sha256: 34398a698b6afcf230f853048e76d9c647cd89663171ef0372eb3ea16a8f5f65

build:
  entry_points:
    - skelly_viewer = skelly_viewer.__main__:run
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - pytest
    - numpy ==1.26.2
    - rich ==13.7.0
    - pyside6 >=6.7.2
    - opencv ==4.8.*
    - pandas ==2.1.*
    - matplotlib-base ==3.8.2
    - __linux
    - xorg-libx11

test:
  imports:
    - skelly_viewer
  commands:
    - skelly_viewer --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/freemocap/skelly_viewer
  summary: View a skelly
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - roaldarbol
